modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Meldexun/BetterDiving/issues"
[[mods]]
modId="better_diving"
version="1.0.0"
displayName="Better Diving"
credits="Thank you Xemnes for providing the oxygen gui and seamoth gui textures."
authors="Meldexun"
description='''
TODO
'''
